# .github/workflows/ci-cd.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: Dexarc/DevSecOps-GCP@v2

      - name: Set up Docker
        uses: Dexarc/DevSecOps-GCP@v3
        with:
          dockerfile: app/Dockerfile
          context: .

      - name: Build and Push Docker Image
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          echo $GITHUB_TOKEN | docker login -u _json_key --password-stdin https://gcr.io
          docker build -t gcr.io/$PROJECT_ID/your-node-app:$GITHUB_SHA ./app
          docker push gcr.io/$PROJECT_ID/your-node-app:$GITHUB_SHA

  terraform_apply:
    needs: build_and_push_docker_image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          terraform apply -auto-approve -var="gcp_project=${GCP_PROJECT_ID}"

  deploy_to_cloud_run:
    needs: terraform_apply
    runs-on: ubuntu-latest

    steps:
      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Google Cloud Run
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          gcloud auth configure-docker
          docker pull gcr.io/$PROJECT_ID/your-node-app:$GITHUB_SHA
          docker tag gcr.io/$PROJECT_ID/your-node-app:$GITHUB_SHA gcr.io/$PROJECT_ID/your-node-app:latest
          gcloud run deploy your-node-app \
            --image gcr.io/$PROJECT_ID/your-node-app:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
